server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/neutron-db?useSSL=false
    username: neutron
    password: Asdqwe123#
    driver-class-name: org.postgresql.Driver
  redis:
    host: localhost
    port: 6380
    database: 0
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2
    timeout: 5000
